set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'brendandebeasi/tabby'
# set -g @plugin 'Freed-Wu/tmux-status-bar'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'lloydbond/tmux-floating-terminal'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g prefix C-a
set -g mouse on
set-option -g default-command zsh
set -g extended-keys on
set -sa terminal-features 'xterm*:extkeys'
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',*:Tc'

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; if-shell "test -f ~/.tmux.conf" "source-file ~/.tmux.conf"

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#[align=absolute-centre]#[fg=#{@thm_fg}]%H:%M:%S | 岩酱可爱捏ovo"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#[fg=#{@_ctp_status_bg},reverse]"

run '~/.tmux/plugins/tmux/catppuccin.tmux'
run '~/.tmux/plugins/tmux-cpu/cpu.tmux'
run '~/.tmux/plugins/tmux-battery/battery.tmux'
run '~/.tmux/plugins/tpm/tpm'